### ISSUE TITLE
"OSError: [WinError 123] Invalid name: '/tmp\\*' despite 'src' directory. 

### ISSUE THREAD

**Issue by akai-katto** [JackMcKew/pyinstaller-action-windows#10]
Hello, I was trying to give the plugin a try. The python code of my project is located under 'src', so I tried running the default config you provided, but ran into the issue you described in the FAQ.

The build log can be found here:

https://github.com/akai-katto/dandere2x/runs/1788803209?check_suite_focus=true

The workflow config can be found here

https://github.com/akai-katto/dandere2x/blob/master/.github/workflows/main.yml

And my python source directory is here:

https://github.com/akai-katto/dandere2x/tree/master/src

Let me know if you see anything wrong, I'm not sure if I'm missing something / I'm still learning Github actions.

**Comment by AndersSteenNilsen** [comment]
I had initially the same problem, then I moved the requirements.txt file into src/ and it worked. Maybe you could try to create a .spec file inside src/ ?

Either the way, I think this action could use some better error-messages?😅

**Comment by Anders-Steen** [comment]
Try to remove your *.spec from .gitignore and upload a .spec file.

**Comment by Myrnedraith** [comment]
> Try to remove your *.spec from .gitignore and upload a .spec file.

This works; alternatively, you can also tell it to use the python file specifically as the spec if you aren't doing anything special like a single file.
