### ISSUE TITLE
ModuleNotFoundError: No module named 'websockets'

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [JackMcKew/pyinstaller-action-windows#14]
Strange issue that I can only reproduce with this script. I can build from the CLI with the `.spec` script but when I build it using this action I get the following error:

```
ModuleNotFoundError: No module named 'websockets'
```

I was trying to figure out if there are additional params required to get this to work but I can't find them in the docs!

**Comment by JackMcKew** [comment]
Have you provided a `requirements.txt` in the `src` folder that also includes the `websockets` dependancy?

**Comment by Nathan-Nesbitt** [comment]
Ah that fixed it, thank you!
