### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'hooksconfig'

### ISSUE THREAD

**Issue by cjlynch278** [JackMcKew/pyinstaller-action-windows#18]
When using the main.spec file generated from the pyinstaller run, I get the following error when running the build during the pyinstaller step - TypeError: __init__() got an unexpected keyword argument 'hooksconfig'.

Here's the erroneous part of my .spec file:
  ```
a = Analysis(['__main__.py'],
               pathex=['C:\\Users\\christopher164141\\PycharmProjects\\SqlMetadata\\src'],
               binaries=[],
               datas=[],
               hiddenimports=[],
               hookspath=[],
               runtime_hooks=[],
               hooksconfig={},
               excludes=[],
               win_no_prefer_redirects=False,
               win_private_assemblies=False,
               cipher=block_cipher,
               noarchive=False)
```

To fix the issue I simply removed the "hooksconfig={}," line from the .spec file. 

The action works as expected now, but I figured I'd document the issue for others running into the problem. Thanks creating this project, it works great for me!

**Comment by porridge** [comment]
Faced the same issue today, and the workaround of removing that kwarg helped. My `.spec` file was created with pyinstaller 4.6. It would be great if @JackMcKew could document what versions of pyinstaller are tested/supported.

**Comment by JackMcKew** [comment]
The source dockerfile specifies which versions of python/pyinstaller are used 

https://hub.docker.com/r/cdrx/pyinstaller-windows

**Comment by jdev082** [comment]
I am experiencing this issue and can't figure out how to fix it.
https://github.com/JaydenDev/AuraPad

**Comment by cjlynch278** [comment]
> I am experiencing this issue and can't figure out how to fix it.
> 
> https://github.com/JaydenDev/AuraPad

Remove the "hooksconfig ={}" line from your aurapad.spec file and rerun, it should go

**Comment by jdev082** [comment]
> > I am experiencing this issue and can't figure out how to fix it.
> > https://github.com/JaydenDev/AuraPad
> 
> Remove the "hooksconfig ={}" line from your aurapad.spec file and rerun, it should go

k

**Comment by SaffatHasan** [comment]
> The source dockerfile specifies which versions of python/pyinstaller are used
> 
> https://hub.docker.com/r/cdrx/pyinstaller-windows

Looks like the base image is using version 3.6 but PyInstaller is currently at version 5.1

**Comment by JackMcKew** [comment]
Please try the solution in the thread: https://github.com/JackMcKew/pyinstaller-action-windows/issues/34
