### ISSUE TITLE
Choose Python version

### ISSUE THREAD

**Issue by flolbr** [JackMcKew/pyinstaller-action-windows#19]
Is there any way to easily specify the python version that will be used by the action ?

**Comment by JackMcKew** [comment]
Potentially you could pass an ARG to the base dockerfile to change the python/pyinstaller version

Souce dockerfile that is used by this project: https://hub.docker.com/r/cdrx/pyinstaller-windows

**Comment by squigjess** [comment]
> Potentially you could pass an ARG to the base dockerfile

I'm not too familiar with GitHub workflows; how would one accomplish this?

**Comment by FlorianCassayre** [comment]
I'm confused as well; could you be more specific? Thanks in advance.

**Comment by sayyid5416** [comment]
Yes, it is a serious issue, since action is failing because of different python versions.

![image](https://user-images.githubusercontent.com/78584556/147532375-92e3bd91-423f-4dae-934f-d8fe64ede990.png)

**Comment by JackMcKew** [comment]
Unfortunately to set the python version through an ARG would include building the new image and pushing it somewhere else (ie, docker hub), so this might be a bit tricky

The way official python dockerfiles are to be built for each and every version which is out of the scope of this project

**Comment by JackMcKew** [comment]
The potential solution for this might be by running certain steps in bash to implement the different versions of Python: https://github.com/JackMcKew/pyinstaller-action-windows/issues/17

**Comment by JackMcKew** [comment]
Please try this: https://github.com/JackMcKew/pyinstaller-action-windows/issues/34
