### ISSUE TITLE
EOFError - with command line input

### ISSUE THREAD

**Issue by MarketingPip** [JackMcKew/pyinstaller-action-windows#21]
Error:   
 
     
       File "build.spec", line 8, in <module>
         dirName =  str(input('Insert the path of your files :'))
    EOFError: EOF when reading a line
    Insert the path of your files :

Tried passing this error with an except but still won't work. Thinking it has to do something with the Windows compiler for Linux if I am right in saying?

Thanks for your awesome work on this script as well! :+1: 

PS; Maybe add an option to auto build the spec file into the dist on first run if not found! 

Another ps; Linux Action isn't working properly. Name-of-artifact.zip only contains the files trying to be built with no executable for Linux.

**Comment by JackMcKew** [comment]
I don't think I'm too keen on the auto build spec as it'll inevitably lead to users not being aware of their spec file which details exactly what they want

Have you got a way to reproduce your error?
