### ISSUE TITLE
python and pyinstaller versions

### ISSUE THREAD

**Issue by inferense** [JackMcKew/pyinstaller-action-windows#25]
thanks for making the action. However when I run install requirements.txt which installs `python 3.9.10` and `pyinstaller 5.0`, the following pyinstaller-action-windows starts building with `python 3.7.5` and `pyinstaller 3.6` which ends up in non-functional pyinstaller exe.

any ideas how to keep the dependency version from requirements.txt?

**Comment by JackMcKew** [comment]
Related issue to do with Python version, TL;DR, it's complex

https://github.com/JackMcKew/pyinstaller-action-windows/issues/19

**Comment by JackMcKew** [comment]
Please try this:

https://github.com/JackMcKew/pyinstaller-action-windows/issues/34
