### ISSUE TITLE
Support custom commands

### ISSUE THREAD

**Issue by jurf** [JackMcKew/pyinstaller-action-windows#26]
Hey,

would it be possible to add support for custom commands? I generate my app from a [Python script](https://pyinstaller.org/en/stable/usage.html?highlight=__main__#running-pyinstaller-from-python-code), so currently I cannot use this, although it would otherwise be very useful for me.

I don’t mind creating a PR if you are ok with it.

**Comment by JackMcKew** [comment]
G'day!

Please feel more than welcome to open a PR :)

**Comment by JackMcKew** [comment]
Closing due to stale

**Comment by jurf** [comment]
Yeah, I did try to do this but quickly realised that I have to build my own container anyway to get it working for my app. :/

**Comment by JackMcKew** [comment]
If you'd like to submit a PR with a docker image, this is how it can be achieved:

https://github.com/JackMcKew/pyinstaller-action-linux/tree/python3.10/Dockerfiles
