### ISSUE TITLE
Support for tkinter

### ISSUE THREAD

**Issue by danieliser** [JackMcKew/pyinstaller-action-windows#27]
I saw the linux version had support for it, wondering if the Windows version could do that as well?

**Comment by JackMcKew** [comment]
G'day mate,

Have you got a specific error of tkinter not working on Windows?

**Comment by danieliser** [comment]
No I’m trying to use the actions to build windows exe files on change to main branch, but it fails to build without tkinter installed and from what I can tell I can’t use `requirements.txt` to install it like normal packages. At least I got errors when I tried.

that led me to find you specific action that also installed `tkinter`, but that is on Linux and won’t handle building Windows `.exe` from my testing.

**Comment by danieliser** [comment]
![352AEE97-9B23-49ED-8645-74932CA288BC](https://user-images.githubusercontent.com/847818/189967252-41709347-4dd0-481b-9060-55d595a8a6de.png)

**Comment by JackMcKew** [comment]
Can you please provide a reproducible example?

**Comment by ego-lay-atman-bay** [comment]
The package name for tkinter is actually `tk`. You need to replace
```
tkinter==8.6
```
with
```
tk==8.6
```
in the requirements.txt

**Comment by Mattherix** [comment]
> ```
> tk==8.6
> ```
> 
> in the requirements.txt

[Tk](https://pypi.org/project/tk/) stands for TensorKit. It's a small library for deep learning.

You can't install tkinter using pip.

**Comment by chrisdeely** [comment]
I believe `tkinter` is part of the Python distribution and as such should not be listed in the `requirements.txt`. The error shown above is because the package does not exist in `pip` so the installation fails.
