### ISSUE TITLE
Program(exe file) gets closed as soon as it open

### ISSUE THREAD

**Issue by musman920** [JackMcKew/pyinstaller-action-windows#29]
Hi 
In my local system , if I build the exe from pyinstaller <filename>.spec then it works fine.
from the github actions artifact. The exe file closes as soon as i open it.

what could be the underlying problem as no error is displayed.

Thank you.
@JackMcKew

**Comment by musman920** [comment]
It is because the packager did not consider hidden imports from .spec file

**Comment by PLanB2008** [comment]
Is there a workaround for this?

**Comment by JackMcKew** [comment]
Can you provide a reproducible example?

**Comment by musman920** [comment]
remove the following line from spec file:

 hooksconfig={},

 This is recommended by the github actions as it is a known/common error with the package.

**Comment by JackMcKew** [comment]
Marking as complete :) Thank you @musman920
