### ISSUE TITLE
false positive on virustotal.com ?

### ISSUE THREAD

**Issue by darodi** [JackMcKew/pyinstaller-action-windows#33]
I tried building an app with your action.
I'm getting 

> 2 security vendors and no sandboxes flagged this file as malicious

on virustotal.com

https://www.virustotal.com/gui/file/d0b96d5b2619fd3da937c8b3449eddefc2bf2866d8fdcd40120df439f27daa4a/detection

Any advice?

**Comment by JackMcKew** [comment]
This is super interesting!

What happens if you compile an app using pyinstaller on your machine?

**Comment by darodi** [comment]
@JackMcKew 

Same thing.
This is a known problem:
https://github.com/pyinstaller/pyinstaller/issues/6754
