### ISSUE TITLE
Default output of "icon" parameter in spec from pyinstaller 5.10.0 changed, incompatible.

### ISSUE THREAD

**Issue by ggppjj** [JackMcKew/pyinstaller-action-windows#36]
Hello!

It would seem that pyinstaller 5.10.0 generates the "icon" property in the spec file as a list, which the version used on both main and the python3-10-pyinstaller-5-3 branches aren't able to figure out. 

I mainly wanted to open the issue as a reference for others, because for some reason it was really hard for me to debug and caused quite a lot of frustration on my end.

Specifically, 5.10.0 generates icon as "icon=['ICON.ico'],", and earlier versions appear to expect "icon='ICON.ico',".

I've solved this in my own code, but could not find an open issue detailing this here, so wanted to make you aware if not already.

**Comment by JackMcKew** [comment]
Thank you for raising this! I'm sure that would've been super annoying

This is not an issue with this action, we simply make use of Pyinstaller here, this is more an issue with version management within Pyinstaller and is why I'm apprehensive around making version 5.10 the standard at the moment
