### ISSUE TITLE
How to build a x86 exe

### ISSUE THREAD

**Issue by anonymousException** [JackMcKew/pyinstaller-action-windows#48]
The default architecture is x64 which can not running on x86 system

**Comment by JackMcKew** [comment]
Can you elaborate on what this impacts?

**Comment by anonymousException** [comment]
> Can you elaborate on what this impacts?

Just compatibility , x64 program can only run under the x64 system.
If the user's system is win7 32 bit or win10 32 bit , it does not work and will show :
![image](https://github.com/JackMcKew/pyinstaller-action-windows/assets/157234942/4f1b6e32-c9f9-42cc-98dd-60bb603bb204)

![image](https://github.com/JackMcKew/pyinstaller-action-windows/assets/157234942/2ce698e5-748c-44e0-b795-66cbac50a158)

**Comment by anonymousException** [comment]
While this may sound outdated, unfortunately some people are still stuck on 32-bit systems

**Comment by JackMcKew** [comment]
Totally understand! Hopefully it's just a configuration in docker to able to support this, would you mind looking into it and opening a PR?

**Comment by anonymousException** [comment]
> Totally understand! Hopefully it's just a configuration in docker to able to support this, would you mind looking into it and opening a PR?

I'm glad to do this, but it may take some more time since I'm not quite familiar with docker

**Comment by JackMcKew** [comment]
Let me know how you go! Always here to help if you need
