### ISSUE TITLE
Support additional arguments

### ISSUE THREAD

**Issue by aj-stein-nist** [JackMcKew/pyinstaller-action-windows#49]
Hello, nice tool and nice work. I have some interest in using additional metadata for a Windows release of a Python app with the `--version-file` argument. Upon quick review of the `entrypoint.sh` script and GHA `action.yaml`, it seems this is not yet supported. Would you be amenable to adding the ability to load additional arguments that do not have dedicated inputs (like spec)? If so, I am willing to help code up this change.

**Comment by aj-stein-nist** [comment]
OK so I figured a workaround to the `--version-file` situation as that doesn't work with a pre-declared and checked in spec file. However, there is another argument I would like to explore, so it still seems like this is worth doing if you are up for it, because I will need to pass in variable values in from GitHub env vars and secrets for the next part.

**Comment by JackMcKew** [comment]
Amazing work!!

If that's the case for environment variables, you should be able to use this action in your own repo (with the env variables) and have access to them, putting them in this repo won't have the effect you're looking for as far as I know

Forking this repo will give you just as much control as I have anyway ☺️

**Comment by aj-stein-nist** [comment]
Of course, I just always like to upstream when I can. Looking at the entrypoint I didn't know if you want the ability to arguments without adding individual input. (I am looking at `--key` with a few others.) If not, no worries.

**Comment by JackMcKew** [comment]
I'm open to absolutely anything if it makes it more functional and flexible!
