### ISSUE TITLE
can you use it just with Docker?

### ISSUE THREAD

**Issue by Schokokex** [JackMcKew/pyinstaller-action-windows#5]
hey, im fiddling around with the docker container in the command line at the moment.
originally i wanted to adjust the github action and add ```pyi-makespec main.py``` or so.. but i gave up :D
does anyone know a way to manually execute the steps?
What i tried: create Docker Image from Dockerfile and entrypoint -> mkdir src and create main.py and main.spec in src -> docker run -it --rm localImage src
then it doesnt find src, of course. any suggestions?

an answer might fit into the Readme.md😉

**Comment by JackMcKew** [comment]
I'd recommend checking out: https://github.com/cdrx/docker-pyinstaller which may be exactly what you're looking for. This github action is just a modified version of it :)

**Comment by JackMcKew** [comment]
Closing due to stale
