### ISSUE TITLE
Build will succeed but exe will fail to start due to ModuleNotFoundError pkg_resources.extern

### ISSUE THREAD

**Issue by rvbg** [JackMcKew/pyinstaller-action-windows#51]
Building an application with the current main version will succeed, but the application will not be able to run, due to `ModuleNotFoundError: No module named 'pkg_resources.extern'`.

This issue has been discussed and fixed here:
#pyinstaller/pyinstaller#8554

Adding `--hiddenimport pkg_resources.extern` or `hiddenimports=['pkg_resources.extern'],` to the .spec file is enough to fix this with the old pyinstaller version used in this action.

**Comment by JackMcKew** [comment]
What do you suggest is the fix for this? Adding documentation to say this is a fix, or upgrading the installer version?

**Comment by rvbg** [comment]
Bumping the pyinstaller version to >=6.7 should be the best, due to the big breaking impact on literally all projects.
Adding few lines to the documentation can't hurt in the meantime :smiley: .

**Comment by JackMcKew** [comment]
Would you like to create a PR for the documentation and I'll add it to my to do to create another docker image with the latest version

**Comment by rvbg** [comment]
Sure, I will create a PR as fast as possible.

**Comment by JackMcKew** [comment]
I'm going to leave this issue open until I get around to creating a new dockerfile

**Comment by axu2** [comment]
Looking forward to a new docker image, subscribing to this issue^. No rush though.

**Comment by JackMcKew** [comment]
I've updated the docker image, thank you for reminding me!
