### ISSUE TITLE
Possible issue with sub folders in src

### ISSUE THREAD

**Issue by stefanino-ch** [JackMcKew/pyinstaller-action-windows#6]
Little test project go get familar with Github Actions:
![working](https://user-images.githubusercontent.com/56797041/103451500-00c34e80-4cc5-11eb-9af7-288b3456bf09.png)

Here in everything works fine. 

If the main py file is in a subfolder in src:
![not-working](https://user-images.githubusercontent.com/56797041/103451511-23edfe00-4cc5-11eb-8cb8-4d26c1e4c059.png)

pyinstaller seems to work fine as github action, no error messages are displayed, BUT no artifacts are created and the following upload reports a warning: 
![warning-message](https://user-images.githubusercontent.com/56797041/103451529-4718ad80-4cc5-11eb-9238-c8cb1b12a755.png)

On the local file system itself, such a configuration is perfectly working, the installers are created. 

Not sure if this is really something which can/ must be fixed. But at least a little warning in the action explanation on the github page would be appreciated.

**Comment by JackMcKew** [comment]
Hey! Thanks for raising this

What was the resulting path of the installer when you ran it locally? I'd take a guess and say that the upload path needs to be altered to match

**Comment by stefanino-ch** [comment]
Yep, classic PIBCAK issue. 
If the path for the upload is set correctly all is working fine. 
![solution](https://user-images.githubusercontent.com/56797041/103451771-34ec3e80-4cc8-11eb-9cb4-effdbfc612e2.png)

I was somehow under the impression the upload path would be the one where the file ends up after copying, nop this is the source path. 
Sorry about.

**Comment by JackMcKew** [comment]
Awesome! Thank you for using the action ☺️
