### ISSUE TITLE
How to set path to root?

### ISSUE THREAD

**Issue by richierh** [JackMcKew/pyinstaller-action-windows#8]
the default setting for path is below
Path : src

but my applications not use src. I use root directory, how to set the yaml file?

**Comment by JackMcKew** [comment]
`path: .` should achieve the outcome you're looking for

**Comment by JackMcKew** [comment]
I take it from your other issue (https://github.com/JackMcKew/pyinstaller-action-windows/issues/9), that this has been resolved. Feel free to open again if this is not the case.
